spring:
  profiles:
    include:
      - domain   # domain 의 yml 에 정의된 데이터 소스관련 내용을 가져온다.
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 80   # 충돌이 일어나지 않게 api(메인) 의 포트 지정